name: Auto-Update via SSH & Generate .env

on:
  workflow_dispatch:  # ðŸ‘ˆ Allows manual execution

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Connect to Server & Update Code
        run: |  
          ssh -i ${{ secrets.SSH_PRIVATE_KEY}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            sudo su
            cd ${{ vars.HOST_DIR }}
            echo "âš™ï¸ ExÃ©cution du script..."
            ./run_setup_frappe.sh
            echo "âœ… Script terminÃ©s sur le serveur !"
          EOF