name: Auto-Update via SSH & Generate .env

on:
  workflow_dispatch:  # ðŸ‘ˆ Allows manual execution

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”‘ Set up SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸš€ Connect to Server & Update Code
        run: |  
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }} << 'EOF'
            sudo su
            cd ${{ vars.HOST_DIR }}
            echo "âš™ï¸ ExÃ©cution du script..."
            ./run_setup_frappe.sh
            echo "âœ… Script terminÃ©s sur le serveur !"
          EOF